Audit changes
SharedStake/Contracts pull request #11
Opened 2021-03-19 16:29 UTC by 0knxwledge

I have completed all but 3 of the changes for #10 

The 3 remaining changes may need some discussion on how to resolve.

1. MIN-01M: The donate() function directly updates the state of the contract, namely the
curValidatorShares state variable, yet it publicly accessible and does not restrict the input
values.
2. VET-01M: The minters of the system can arbitrarily burn tokens.
3.The linked require statements do not restrict the subsequent functionality, as the
conditionals will always yield true .

2021-03-21 00:01 UTC, sharedStake-dev requested changes

2021-03-21 00:01 UTC, sharedStake-dev commented on Minter_v1.0.1.sol
> +        this.migrateShares(shares);
lets remove this call perhaps?  
Since it'll be called by the new sharedDeposit contract, and the new sharedDeposit contract is not an owner of the old sharedDeposit contract, im not 100% sure if it will work.

2021-03-21 00:01 UTC, sharedStake-dev commented on Minter_v1.0.1.sol
> +    function migrateShares(uint256 shares) external payable onlyOwner nonReentrant {
this doesnt need to be payable

2021-03-21 04:45 UTC, 0knxwledge commented on Minter_v1.0.1.sol
> +        this.migrateShares(shares);
agreed - removed the function call.

2021-03-21 04:46 UTC, 0knxwledge commented on Minter_v1.0.1.sol
> +    function migrateShares(uint256 shares) external payable onlyOwner nonReentrant {
removed payable

2021-03-22 19:41 UTC, sharedStake-dev approved these changes

2021-03-22 20:00 UTC, sharedStake-dev commented on Minter_v1.0.1.sol
>          uint256 newShareTotal = curValidatorShares.sub(amount);
this line will overflow and throw so the following is no longer needed:

```
  require(
            newShareTotal >= 0,
            "Eth2Staker:withdraw:Amount too small, not enough validators left"
        );
 ```

2021-03-24 17:18 UTC, sharedStake-dev commented on Minter_v1.0.1.sol
> -        require(
As the withdraw function burns vETH2 to return ETH, it is impossible for it to increase the `newShareTotal`. Therefore this require is basically a no-op.

2021-04-01 01:17 UTC, merged